
export default new Map([
["src/content/posts/10-personajes-celebres-mexicanos.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2F10-personajes-celebres-mexicanos.mdx&astroContentModuleFlag=true")],
["src/content/posts-temp/calumnia-de-apeles.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts-temp%2Fcalumnia-de-apeles.mdx&astroContentModuleFlag=true")],
["src/content/posts-temp/8-curiosidades-sobre-coco.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts-temp%2F8-curiosidades-sobre-coco.mdx&astroContentModuleFlag=true")],
["src/content/posts-temp/covadonga-historica.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts-temp%2Fcovadonga-historica.mdx&astroContentModuleFlag=true")],
["src/content/posts-temp/la-playa-mas-pequena-de-espana.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts-temp%2Fla-playa-mas-pequena-de-espana.mdx&astroContentModuleFlag=true")],
["src/content/posts-temp/jardin-de-las-delicias.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts-temp%2Fjardin-de-las-delicias.mdx&astroContentModuleFlag=true")],
["src/content/posts-temp/la-sensualidad-del-vuelo.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts-temp%2Fla-sensualidad-del-vuelo.mdx&astroContentModuleFlag=true")],
["src/content/posts-temp/la-tragedia-del-naufragio.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts-temp%2Fla-tragedia-del-naufragio.mdx&astroContentModuleFlag=true")],
["src/content/posts-temp/la-sirenita-george-delatour.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts-temp%2Fla-sirenita-george-delatour.mdx&astroContentModuleFlag=true")],
["src/content/posts-temp/mayo-1808-en-madrid.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts-temp%2Fmayo-1808-en-madrid.mdx&astroContentModuleFlag=true")],
["src/content/posts-temp/paisajes-sublimes-y-personas-de-espaldas.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts-temp%2Fpaisajes-sublimes-y-personas-de-espaldas.mdx&astroContentModuleFlag=true")],
["src/content/posts-temp/ribadesella.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts-temp%2Fribadesella.mdx&astroContentModuleFlag=true")],
["src/content/posts-temp/vermer-hitler-y-la-astronomia.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts-temp%2Fvermer-hitler-y-la-astronomia.mdx&astroContentModuleFlag=true")],
["src/content/posts-temp/ruta-del-cares.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts-temp%2Fruta-del-cares.mdx&astroContentModuleFlag=true")]]);
		